name = "baby-tracker-api"
main = "src/index.ts"
compatibility_date = "2025-05-18"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "baby-tracker"
database_id = "b8407f98-e29f-4a28-9a0d-57f10525fb92"

[vars]
BETTER_AUTH_URL = "https://baby-tracker-api.abbaspuzi-dev.workers.dev"

[dev]
port = 8787
